Added comments in action-mappers.
rms-191216-java-usf/rms-ui pull request #77
Opened 2020-06-11 20:39 UTC by TTHoang97

2020-06-11 21:17 UTC, sthoms3 requested changes
turn into documentation comments pls

2020-06-11 21:44 UTC, jbostik commented on src/App.tsx
> +import HomeComponent from './components/Home-component/HomeContainer';
This should be lower case

2020-06-11 21:44 UTC, jbostik commented on src/App.tsx
> +import EmployeesComponent from './components/Employees-component/EmployeesContainer';
This should be lower case

2020-06-11 21:47 UTC, jbostik requested changes
Please fix the lines I've commented before pushing again. Thanks

2020-06-11 21:47 UTC, jbostik commented on src/App.tsx
> +  // if (this.props.loggedIn) {
this should not be commented

2020-06-11 21:47 UTC, jbostik commented on src/App.tsx
> +    // )
This should not be commented

2020-06-11 21:47 UTC, jbostik commented on src/App.tsx
> +// }
this should not be commented

2020-06-11 21:47 UTC, jbostik commented on src/action-mappers/campus-action.ts
> +//Not sure if update method at the bottom is neccessary when useEffct/useState should run getAll again and display all of the new data.
This should be one single documentation comment

2020-06-11 21:47 UTC, jbostik commented on src/action-mappers/employees-action.ts
> +//Not sure if update method at the bottom is neccessary when useEffct/useState should run getAll again and display all of the new data.
These should be one single documentation comment

2020-06-11 21:47 UTC, jbostik commented on src/action-mappers/room-details-actions.ts
> +//Need to add in proper methods instead of a mock method.
These should be one single documentation comment

2020-06-12 14:50 UTC, jbostik approved these changes

2020-06-12 15:20 UTC, sthoms3 approved these changes

2020-06-12 15:24 UTC, wandeltk approved these changes
Looks good to me!

2020-06-12 15:24 UTC, merged